openapi: 3.0.0
info:
  title: Event Service
  version: 1.0.0
servers:
  - url: http://localhost:8081
paths:
  /date/dates:
    $ref: './api/date.yaml#/paths/~1dates'
  /date/dates/{Id}:
    $ref: './api/date.yaml#/paths/~1dates~1{Id}'
  /location/location:
    $ref: './api/locations.yaml#/paths/~1location'
  /location/{Id}:
    $ref: './api/locations.yaml#/paths/~1location~1{Id}'
  /status:
    $ref: './api/status.yaml#/paths/~1status'
  /status/{Id}:
    $ref: './api/status.yaml#/paths/~1status~1{Id}'
  /team-action-status:
    $ref: './api/team_action_status.yaml#/paths/~1team-action-status'
  /team-action-status/{TimelineId}/{TeamId}:
    $ref: './api/team_action_status.yaml#/paths/~1team-action-status~1{TimelineId}~1{TeamId}'
  /timeline:
    $ref: './api/timeline.yaml#/paths/~1timeline'
  /timelime/status:
    $ref: './api/timeline.yaml#/paths/~1timeline~1status'
  /timeline/{Id}:
    $ref: './api/timeline.yaml#/paths/~1timeline~1{Id}'
