openapi: 3.0.0
info:
  title: Event Service
  version: 1.0.0
servers:
  - url: http://localhost:8081
paths:
  /location:
    $ref: '../api/locations.yaml#/paths/~1location'
  /location/{Id}:
    $ref: '../api/locations.yaml#/paths/~1location~1{Id}'