openapi: 3.0.0
info:
  title: Event Service
  version: 1.0.0
servers:
  - url: http://localhost:8081
paths:
  /status:
    $ref: '../api/status.yaml#/paths/~1status'
  /status/{Id}:
    $ref: '../api/status.yaml#/paths/~1status~1{Id}'