openapi: 3.0.0
info:
  title: Event Service
  version: 1.0.0
servers:
  - url: http://localhost:8081
paths:
  /team-action-status:
    $ref: '../api/team_action_status.yaml#/paths/~1team-action-status'
  /team-action-status/{TimelineId}/{TeamId}:
    $ref: '../api/team_action_status.yaml#/paths/~1team-action-status~1{TimelineId}~1{TeamId}'
