openapi: 3.0.0
info:
  title: Event Service
  version: 1.0.0
servers:
  - url: http://localhost:8081
paths:
  /timeline:
    $ref: '../api/timeline.yaml#/paths/~1timeline'
  /timelime/status:
    $ref: '../api/timeline.yaml#/paths/~1timeline~1status'
  /timeline/{Id}:
    $ref: '../api/timeline.yaml#/paths/~1timeline~1{Id}'
