env: "local"
auth-url: "http://user_and_teams_service:8000/api/v0/auth/auth-check"
http_server:
  address: ":8081"
  timeout: 10s
  idle_timeout: 60s
sql_database:
  addr: "postgres:5432"
  user: "admin"
  password: "admin"
  database: "postgres"
  echo: false
  echo_pool: false
  pool_size: 50
  max_overflow: 10

